### ISSUE TITLE
does not support bar charts

### ISSUE THREAD

**Issue by psyantyst** [bendichter/brokenaxes#11]
Great tool! Unfortunately it does not support plotting a Pandas dataframe as a bar chart. As I understand, it supports only line charts.

**Comment by bendichter** [comment]
It doesn't support `df.plot(ax=bax, kind='bar')` but it should support `bax.bar`

**Comment by psyantyst** [comment]
Still, I don't see how to plot a Pandas dataframe as bar. This is how I do it so far:
```
import pandas as pd
dt = pd.DataFrame(...)
dt.plot.bar()
```
Not sure how this tool can help me split the vertical axis to show outliers.

**Comment by bendichter** [comment]
Yeah you need to make the bar plot yourself with plt. See the example in the readme.

**Comment by psyantyst** [comment]
Correct, after converting the Pandas dataframe to an array I can plot the bar chart with `bax.bar(...)`. 
![download](https://user-images.githubusercontent.com/7893670/37512576-d3d39f9e-2902-11e8-9968-51fb2c121b7c.jpg)

Of course, the column/index label information from the dataframe is lost, but it's not too big of a deal to keep it separate.

**Comment by bendichter** [comment]
Good luck with the project!
