### ISSUE TITLE
y axis labels appear in the break space

### ISSUE THREAD

**Issue by rguliev** [bendichter/brokenaxes#120]
Demo data: [xy.csv.zip](https://github.com/user-attachments/files/16246811/xy.csv.zip)

```python
import matplotlib.pyplot as plt
from brokenaxes import brokenaxes

# Load the data
df = pd.read_csv("xy.csv.zip")
x = df.x.values
y = df.iloc[:,1:].values

# Plot the data
fig = plt.figure(figsize=(5, 2))
bax = brokenaxes(xlims=((400, 1800), (2650, 3100)), wspace=0.1)
bax.plot(x, y)
plt.show()
```

![image](https://github.com/user-attachments/assets/6e2a2a9e-3da5-4b3e-8ecb-278117301e52)

**Comment by bendichter** [comment]
huh, very interesting bug, thanks for the report. I have no idea why this is happening, but I did find a way to fix it
