### ISSUE TITLE
bax.grid() doesn't allow plotting gridlines (consistent across all the subplots)

### ISSUE THREAD

**Issue by pharshalp** [bendichter/brokenaxes#13]
Following example (slightly modified version of one of the examples in the documentation) shows that the current version of brokenaxes doesn't allow plotting gridlines (consistent across all the subplots).

```
import matplotlib.pyplot as plt
from brokenaxes import brokenaxes
import numpy as np

fig = plt.figure(figsize=(6,3))
bax = brokenaxes(xlims=((0, .1), (.4, .7)), ylims=((-1, -0.5), (.5, 1)),
	             hspace=.1, wspace=.1)
x = np.linspace(0, 1, 100)
bax.plot(x, np.sin(10 * x), label='sin')
bax.plot(x, np.cos(10 * x), label='cos')
bax.legend(loc=3)
bax.set_xlabel('time')
bax.set_ylabel('value')
bax.minorticks_on()
bax.grid(axis='both', which='major', ls='-')
bax.grid(axis='both', which='minor', ls='--', alpha=0.5)
plt.show()
```

**Old behavior:**
![old](https://user-images.githubusercontent.com/15175620/37877841-8a3f361c-302e-11e8-834a-a46f46c1924a.png)

I have submitted a pull request #12 to fix this (since this is my first time submitting a PR, I wasn't sure whether I should be posting this as an issue as well).

**New behavior:**
![improved](https://user-images.githubusercontent.com/15175620/37877848-8fd4175a-302e-11e8-9ffb-de1125b6ea0c.png)

**Comment by bendichter** [comment]
@pharshalp You did a great job on this! Thanks so much for contributing!
