### ISSUE TITLE
How to share x axes in subplots?

### ISSUE THREAD

**Issue by Kal-Elll** [bendichter/brokenaxes#14]
I creat subplots with Gridspec, how can I make the top panel share the x axes with the bottom one?

**Comment by bendichter** [comment]
@Kal-Elll I'd probably set the xlims as the same for both plots. If you give me some example code I can be more specific.

**Comment by Kal-Elll** [comment]
![image](https://user-images.githubusercontent.com/21331868/39060790-f2b228ae-4487-11e8-80c6-570a8bb45a19.png)
I mean something like this figure. Two panels have the same range and limits of x. The x axes of the top panel shows no label. I have solved my problem using set_xticklabels([]). Thanks a lot!!

**Comment by bendichter** [comment]
ah ok yeah I see what you mean. That sounds like the right solution. Closing.
