### ISSUE TITLE
wspace and hspace have no effect and are not initialized

### ISSUE THREAD

**Issue by tvajtay** [bendichter/brokenaxes#15]
I was trying to see if I could define the space in between the diagonal ticks and saw in the example;

    bax = brokenaxes(xlims=((0, .1), (.4, .7)), ylims=((-1, .7), (.79, 1)), hspace=.05)

However when I try to run this example changing hspace doesn't do anything and when I looked at the code hspace and wspace are of type bool but have no usage in the code.

**Comment by tvajtay** [comment]
Never mind, rookie mistake. forgot that ``` *args, **kwargs``` where going to pass hspace and wspace to gridspec, it was always working, I just didn't go low enough for the ratio. My mistake.

**Comment by bendichter** [comment]
No worries. Thanks for using brokenaxes!
