### ISSUE TITLE
log scale when one of the axis is not broken

### ISSUE THREAD

**Issue by lulelita** [bendichter/brokenaxes#19]
Hi there,
 Thank you for doing brokenaxes, such a useful little package! 
I am trying to use brokenaxes to do a figure for my current paper and I have a question regarding the log scale:

I want to break the x-axis (not the y-axis) but I do want the plot to be in log scale in the y-axis. Is this possible?
So far I have found that if I put the option yscale=log but leave the breaks for the y-axis empty, I get an error.
Please see below a MWE:

import numpy as np
from brokenaxesUpdated import brokenaxes
import matplotlib.gridspec as gridspec
from matplotlib import pyplot as plt

tstart0 = 0
tfinal0 = 60
delta_t = 0.1
num_steps = np.floor((tfinal0 - tstart0) / delta_t) + 1
tspan0 = np.linspace(tstart0, tfinal0, num_steps)

gs = gridspec.GridSpec(3, 3)
for kvals in range(3):
    bax = brokenaxes(xlims=((1, 14), (60, 74)),  hspace=0.5,
                     subplot_spec=gs[kvals, 0],
                     yscale='log')
    bax.plot(tspan0, tspan0)

plt.show()

The error that I get is:
TypeError: __init__() got an unexpected keyword argument 'yscale'

PS I had to create an "updated" local version of brokenaxes in my computer for it to include the log scale option, as downloading it with pip install didn't download the newest version

**Comment by bendichter** [comment]
Thanks for reporting the bug. Should be fixed with the push just a minute ago. Try this:
```python
bax = brokenaxes(xlims=((1, 8), (9, 10)), hspace=.15, yscale='log')
x = np.linspace(0.0, 10, 100)
bax.semilogy(x,x)
```

**Comment by bendichter** [comment]
I'd also recommend using `hspace` with the `gridspec` call:

```python
import numpy as np
import matplotlib.gridspec as gridspec
from matplotlib import pyplot as plt

tstart0 = 0
tfinal0 = 60
delta_t = 0.1
num_steps = np.floor((tfinal0 - tstart0) / delta_t) + 1
tspan0 = np.linspace(tstart0, tfinal0, num_steps)

gs = gridspec.GridSpec(3, 3, hspace=.5)
for kvals in range(3):
    bax = brokenaxes(xlims=((1, 14), (60, 74)),  hspace=0.5,
                     subplot_spec=gs[kvals, 0],
                     yscale='log')
    bax.plot(tspan0, tspan0)
```
