### ISSUE TITLE
tight_layout() support?

### ISSUE THREAD

**Issue by andrisecker** [bendichter/brokenaxes#20]
Cool package! Are you planning to add `fig.tight_layout()` support?
I get an error message: `warnings.warn("This figure includes Axes that are not compatible "` and the lines which break the axes get shifted (outside of the axis) when trying to use `tight_layout()`

**Comment by bendichter** [comment]
Can you clarify what the desired behavior would be? Would the gaps between the axes of the brokenaxes plot change, or just the position of the entire brokenaxes plot?

In the meantime you should be able to get your desired results by tweaking `hspace` and `wspace` in `GridSpec`

**Comment by andrisecker** [comment]
The position of the entire plot. Yes I started to tweak the `GridSpec`

**Comment by gabeycas** [comment]
I have having a hard time with BrokenAxis, with Matplotlib completely clipping the x and y labels of a plot. Tight/constrained layouts were not solving the problem (and also moving the line breaks as mentioned above.) In my case, the figure was small (2.75"x3"), where matplotlib can have a hard time placing axes into the plot area.

I eventually found that the issue is the default x & y offsets, set with the labelpad argument for `BrokenAxis.set_*_axis()` function. By passing GridSpec left and bottom parameters like this
`bax = brokenaxes.brokenaxes(xlims=((L,R) left = 0.25, bottom = 0.25)`
and then setting the labels as
`bax.set_xlabel("x label", labelpad = 0)`
`bax.set_ylabel("y label", labelpad = 0)`,
I got a the desired result, with labels on the figure -- the same outcome as tight_layout() would have on a simpler figure. I'm not sure whether or not there is a way to make this automatic, but this manual solution does let you use this package to create small plots that save correctly with `plt.savefig()`.

**Comment by bendichter** [comment]
fig.tight_layout() should work now

**Comment by ephilalethes** [comment]
Using `fig.tight_layout()` doesn't seem to work well for me, as I also get `UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.`, and the plot looks messed up in many ways:

![Figure_1](https://github.com/bendichter/brokenaxes/assets/171831907/e3794b6c-5170-4002-a57b-afebf87a2547)

The break marks are misplaced, the x-label collides with the x-tick labels, the y-tick labels are outside of the screen, and it's not using the x-ticks I set it to (should be from 0 to 360, having used `bax.set_xticks(range(0, 360 + 1, 10))`.

Maybe it's just me doing something wrong though; any pointers?

**Comment by bendichter** [comment]
@ephilalethes could you provide some self-contained code that reproduces this behavior?

**Comment by ephilalethes** [comment]
@bendichter:

Sure, here is the script I'm running (it needs Requests, hopefully that's fine):

```
from datetime import datetime as dt, timedelta as td
import requests as req
import matplotlib.pyplot as plt
from brokenaxes import brokenaxes

clonurl = ("http://jsoc.stanford.edu/cgi-bin/ajax/showextinfo?ds=hmi.sharp_720s_nrt%5B", "%5D&key=CRLN_OBS%2CLON_FWT%2CNOAA_AR&seg=&dbhost=hmidb2&t=1&i=1&K=0&n=0&a=0&A=0&P=0&r=0&S=0&z=0&o=0&R=0&x=0")

regs = [9997, 10149, 10285]
#regs = range(9997, 10286)
rurls = [clonurl[0] + str(r) + clonurl[1] for r in regs]

arcls = []
for reg, rurl in zip(regs, rurls):
    r = req.get(rurl)
    text = r.text.split()
    lines = [' '.join(text[i:i+4]) for i in range(0,len(text),4)][4:]
    lines = [l.split() for l in lines]

    ldts = [dt.strptime(l[0][-24:-5], "%Y.%m.%d_%H:%M:%S") for l in lines]
    clons = [float(l[1]) + float(l[2]) for l in lines]
    clons = [c + 360 if c < 0 else c for c in clons]
    clons = [c - 360 if c > 360 else c for c in clons]
    
    try:
        narn = lines[-1][3]
    except:
        narn = "77777"
    if narn == "0":
        narn = "13723"
    """
    else:
        ldts = ldts[240:-240]
        clons = clons[240:-240]
    """

    staxdt = ldts[0] - td(hours=12)
    enaxdt = ldts[-1] + td(hours=12)

    arcls.append((narn, ldts, clons, reg, staxdt, enaxdt))





fig = plt.figure(figsize=(20, 10))

axdtts = []
for arcl in arcls:
    axdtts.append((arcl[4], arcl[5]))

bax = brokenaxes(ylims=axdtts, hspace=.1)

for arcl in arcls:
    bax.plot(arcl[2], arcl[1], label="AR " + arcl[0] + " (SHARP " + str(arcl[3]) + ")")

bax.set_ylabel("date")
bax.set_xlabel("flux-weighted Carrington longitude of active region (°)")

#ax = bax.gca()
bax.grid(axis="x")

#plt.legend(loc='upper right')

bax.set_xticks(range(0, 360 + 1, 10))
#plt.yticks(range(ll, ul + 1, crs))

#plt.title("flux-weighted Carrington longitudes of active regions over time")

fig.tight_layout()

plt.show()
plt.close()
```

**Comment by bendichter** [comment]
You can use

``python
plt.tight_layout()
for handle in bax.diag_handles:
    handle.remove()
bax.draw_diags()
```

**Comment by ephilalethes** [comment]
Thanks, that does seem to fix the break marks on the axis; some of the other issues appear to still be present though, like the date labels outside of the screen, the break marks also seem to be drawn over the y-tick labels (but maybe I can find some way to draw them shorter), and for some reason the plot has extra ticks (at -10 and 370), with grid lines being drawn for those extra ticks only in the bottommost broken axis, and there's also still some slight overlap of the x-axis label and the x-tick labels.
