### ISSUE TITLE
DateTime axes not supported

### ISSUE THREAD

**Issue by tony-p** [bendichter/brokenaxes#21]
Traceback (most recent call last):
    ax1 = brokenaxes.brokenaxes(xlims=plotbreaks, vspace=1)
  File "..\brokenaxes.py", line 275, in brokenaxes
    return BrokenAxes(*args, **kwargs)
  File "..\brokenaxes.py", line 56, in __init__
    width_ratios = [i[1] - i[0] for i in xlims]
  File "..\brokenaxes.py", line 56, in <listcomp>
    width_ratios = [i[1] - i[0] for i in xlims]
TypeError: 'datetime.datetime' object is not subscriptable

**Comment by bendichter** [comment]
xlims needs to be a list of lists of datetimes.

**Comment by bendichter** [comment]
@tony-p did you sort out your issue? If not, please provide minimal code that generated this error. Otherwise I will close this issue. Thanks!

**Comment by tony-p** [comment]
Sorry yes this did solve my issue ... I’ve been on vacation so missed this.

I didn’t end up using this though as it doesn’t work with interactive PyPlot as the zooming only works on 1 sub part at a time.

**Comment by bendichter** [comment]
Oh, I didn't realize that. Thanks for letting me know
