### ISSUE TITLE
how to set  xticklabels font as 'Times New Roman'  and the fontsize ?

### ISSUE THREAD

**Issue by chaoshengt** [bendichter/brokenaxes#23]
thanks for creating brokenaxes!  
could you tell me how to set  yticklabels font as 'Times New Roman'   and the fontsize  in this example:
```python
from brokenaxes import brokenaxes
from matplotlib.gridspec import GridSpec
import numpy as np

sps1, sps2 = GridSpec(2,1)

bax = brokenaxes(xlims=((.1, .3),(.7, .8)), subplot_spec=sps1)
x = np.linspace(0, 1, 100)
bax.plot(x, np.sin(x*30), ls=':', color='m')

x = np.random.poisson(3, 1000)
bax = brokenaxes(xlims=((0, 2.5), (3, 6)), subplot_spec=sps2)
bax.hist(x, histtype='bar')
```

**Comment by bendichter** [comment]
Thanks for using it! This should work.
https://stackoverflow.com/questions/12322738/how-do-i-change-the-axis-tick-font-in-a-matplotlib-plot-when-rendering-using-lat

Do that to each of bax.axs

**Comment by chaoshengt** [comment]
@bendichter Thanks a lot ! I will try! :)
