### ISSUE TITLE
Change wspace to vspace

### ISSUE THREAD

**Issue by mardukbp** [bendichter/brokenaxes#31]
It is more intuitive to set the vertical spacing with `vspace` than with `wspace`.

Moreover, the parameter is documented, but it is no longer present in the code.

**Comment by bendichter** [comment]
I agree vspace would be more intuitive but I copied the term from matplotlib subplot_adjust and I want to be consistent with other tools

**Comment by bendichter** [comment]
It being removed is a bit concerning

**Comment by pharshalp** [comment]
In matplotlib `wspace` stands for the horizontal (width) spacing and `hspace` stands for the vertical (height) spacing. https://matplotlib.org/api/_as_gen/matplotlib.pyplot.subplots_adjust.html

**Comment by mardukbp** [comment]
I understand the desire to be consistent with mpl. But it is possible to have both the mpl term and the intuitive term. Casual users like me don't care about the idiosyncrasies of mpl. The best user interface is the one that is easy to use and remember.

**Comment by bendichter** [comment]
@mardukbp If you look at the code, you'll see that I never even use this variable, and I pass it directly to the subplot_adjust call. I think it would be harder to maintain if we start using different variable names to mean the same thing. This way is easier for users who are already familiar with mpl, even if it's a bit harder for those who aren't. I'll see if I can make it a bit more clear in the documentation.
