### ISSUE TITLE
Different steps for the different axes

### ISSUE THREAD

**Issue by bieniekmateusz** [bendichter/brokenaxes#36]
Hi there, 

Is it possible to change the steps for the different axes? 
I am trying to divide my graph into two parts where Y axis is a) 1,2, .. 5, / /  b) 20, 40, .. 100

Thanks, Mat

**Comment by bendichter** [comment]
I think you are better off using `plt.subplots` for that.

**Comment by bieniekmateusz** [comment]
Thanks, as pointed out, I used this: https://matplotlib.org/3.1.0/gallery/subplots_axes_and_figures/broken_axis.html

Cheers, Mat
