### ISSUE TITLE
Use brokenaxes with matplotlib rectangel patch

### ISSUE THREAD

**Issue by mangoon91** [bendichter/brokenaxes#41]
I have a rectangle with an x range from 0 - 400000 which I want to compare with other rectangles in the range of 10000 - 100000. I do use a semilogx() plot, but still, the brokenaxes would come really handy to show a break for example between 1 and 1000.

I'd be happy to send you the entire code (150 lines), but for conciseness here is a preview:
------------------------------------
from matplotlib.patches import Rectangle
....
# Create a Rectangle patch
rect = Rectangle((cap_l, eff_l), width, height,alpha=1,fill=False,linewidth=3,color =     Colors[Data.loc[Number,'Technology']])
host.add_patch(rect)
....
------------------------------------
The error message comes for host.add_patch(rect) and is "ValueError: Can not reset the axes. You are probably trying to re-use an artist in more than one Axes which is not supported"

Any idea for a workaround/resolution?

**Comment by bendichter** [comment]
Hmmm looks like patches can't be applied to multiple axes. You could probably do something like
```
from copy import copy
for ax in host.axs:
    rect_copy = copy(rect)
    ax.add_patch(rect_copy)
```

I can't test this right now but I think that will work

**Comment by mangoon91** [comment]
Btw, it worked!
