### ISSUE TITLE
Broken axes with twin axis

### ISSUE THREAD

**Issue by mangoon91** [bendichter/brokenaxes#42]
I want to create a double y axis. The second y axis should NOT be independent, but just show the first y-axis in a different unit (MJ/m3 insteady of kWh/m3). Here is what I have and down below the problems left:

![image](https://user-images.githubusercontent.com/30247060/69738484-78c05c00-1136-11ea-9e2b-7afc9dbb85fd.png)

1. The new axis appears twice, I want it to appear only at the very right (not where the xaxis is broken).
2. I can't add a ylabel for the twin axis. I try:
    secax = host.secondary_yaxis('right', functions=(kWhm3_MJm3,MJm3_kWhm3))
    secax.set_ylabel('Efficiency [MJ/m3]')
But the second line results in the error: "AttributeError: 'list' object has no attribute 'set_ylabel'"

Any help appreciated, let me know if you need my code.
I think the plot will be quite nice and you could certainly publish it on your website as an example.

Thanks much!
Leon

**Comment by bendichter** [comment]
Hi Leon,

`brokenaxes` works by creating a grid of individual axes and setting their positions and data ranges. If you want to do this type of advanced axis control, you'll need to do it to the individual axes, which you can access with `bax.axs`. Then I suppose you would want to set the `visible` property of the left spine of that axes to `False`. Hope that helps.

Ben

**Comment by mangoon91** [comment]
Hi Ben,

I added the line:
host.axs[2].set_visible(False).

Which deletes a bit more than only the axis and also only the bottom part of the broken axis but not the  top part:
![image](https://user-images.githubusercontent.com/30247060/69864299-e1c2e380-129e-11ea-9e53-c34b10e9288a.png)


Any further idea and what I did wrong?

**Comment by bendichter** [comment]
Getting closer. You need to adjust the visibility of the individual spines of that axes

**Comment by mangoon91** [comment]
Hey Ben,

I got yet closer...
![image](https://user-images.githubusercontent.com/30247060/69901042-15c00680-137c-11ea-8da9-a0e160b71994.png)

How can I access the upper part of the broken axis to remove those spines and tick labels? I thought it should work with first_col[0], but that does not seem to be available after I created a twin-axis (using twin = bax.twinx()). It throws this error messages:

![image](https://user-images.githubusercontent.com/30247060/69901081-0097a780-137d-11ea-8293-d5aa8cbd0c7c.png)


How could I remove the remaining spines?

Thanks much,
Leon

**Comment by jehill17** [comment]
@mangoon91 Did you ever resolve this? Running into the same issue. Please let me know if you found a solution.

**Comment by bendichter** [comment]
@jehill17 and @mangoon91, I just pushed a dedicated method for this. See https://github.com/bendichter/brokenaxes/blob/master/examples/plot_second_y_axis.py

**Comment by pintonos** [comment]
@bendichter Hi, thanks for the example. Is there a way for an independent axis? So that the values are not defined via a function, but independently?
