### ISSUE TITLE
Examples use hspace, which seems to have changed to wspace.

### ISSUE THREAD

**Issue by adamjermyn** [bendichter/brokenaxes#43]
Hi,

First, this package is really wonderful! Thank you for maintaining it!

I started using it following the examples but noticed that hspace doesn't do anything. It looks like it changed to wspace at some point. If that's right it would be good if the docs reflected that.

Thanks again!

**Comment by bendichter** [comment]
Hi @adamjermyn 

hspace is working as expected. You may think it stands for "horizontal space" but actually it stands for "height space." If you want to change gaps in the x axis, use wspace (width space). If you think this is confusing, you are not alone. I did not pick these names. I am simply passing them to the `GridSpec` constructors that follow this convention (see [here](https://matplotlib.org/api/_as_gen/matplotlib.gridspec.GridSpec.html#matplotlib-gridspec-gridspec)).
