### ISSUE TITLE
How do I modify the ytick labels when using a histogram

### ISSUE THREAD

**Issue by Penacare** [bendichter/brokenaxes#48]
Hi, I am new at this and don't have any experience but have been able to plot some graphs. I have not been able to change the y-axis ticks. As you can see I wanted to use an abbreviated form instead of having a large tick of 2,000,000. I have been able to do in other plots with the following line of code:
`plt.gca().yaxis.set_major_formatter(EngFormatter())`
but thats for plots that dont need to be broken.

I tried this when using brokenaxes but haven't been able to make any changes to the y-ticks! Hope anyone could help me.

Thanks!

`
from matplotlib import pyplot as plt
from brokenaxes import brokenaxes
import matplotlib.ticker as tck
from matplotlib.ticker import EngFormatter

fig = plt.figure(figsize=[10,6])

bax = brokenaxes(xlims=((1200, 1400), (1800, 2000)))

bax.hist(CHplot, bins=200, range=(1100,2000), label='Cored Hole', alpha=0.75)
bax.hist(RHplot, bins=200, range=(1100,2000), label='Reamed Hole', alpha=0.75)

bax.legend(loc='upper right')

#X-axis
bax.set_xlabel('Time [0.1 µsec]')

#Y-Axis 
bax.set_ylabel('Frequency',labelpad=60)
bax.tick_params(axis='y', labelrotation=45)
bax.set_major_yticklabels=(('500k','1M','1.5M','2M'))

#Grids

bax.set_axisbelow(True)

bax.minorticks_on()

bax.grid(axis= 'x', which='major', linewidth=2, alpha=1)

bax.grid(axis= 'x', which='minor', linestyle='--', linewidth=1, alpha=.5)

bax.grid(axis= 'y', which='major', linewidth=2, alpha=1)

plt.title('Travel-Time Distribution (Well: H-5)')

plt.show()
`

![Travel-Time_Distribution_H-5](https://user-images.githubusercontent.com/65273865/81778953-bbe27180-94c1-11ea-9d21-b92ce0b525b8.PNG)

**Comment by bendichter** [comment]
You can access the individual sub-axes with `bax.axs`. `bax.axs[0].yaxis.set_major_formatter(EngFormatter())` should do it.

**Comment by Penacare** [comment]
Thanks! it works!
