### ISSUE TITLE
Hide the break

### ISSUE THREAD

**Issue by shivanshi13** [bendichter/brokenaxes#49]
Want to hide the break between the axes and want to make it continuous. Any solution?
And also if is it possible to show only one number at the break for this continuous axis?

**Comment by bendichter** [comment]
If you want continuous axes, why are you using this package?

**Comment by bendichter** [comment]
Oh, you want to jump a range on an axis without indicating that using a separation between the axes and a break mark? OK now I understand, but I don't want to help you do that because it sounds like a bad data visualization practice.

**Comment by shivanshi13** [comment]
Yes, sir, that's what I wanted to do.
Yeah, I understand that it's not a good data visualisation practice. It's
ok if you don't want to help.
Thank You
Shivanshi Gupta
