### ISSUE TITLE
Keeping the "top" and "right" spines 

### ISSUE THREAD

**Issue by kennethdistefano** [bendichter/brokenaxes#50]
Hello, I have a naive question about formatting.

I'm having trouble displaying the top, right and middle spines within a group of subplots. For example, I would like to convert this plot
![temp](https://user-images.githubusercontent.com/65573427/84582856-318a7780-adb7-11ea-968e-ecf5cbcd6519.png)

into something like this

![temp1](https://user-images.githubusercontent.com/65573427/84583007-30f2e080-adb9-11ea-8528-cc37b1468974.png)

but with the missing spines and ticks. Is there a way to make those axes visible?

Thank you!!

**Comment by bendichter** [comment]
The top and right are easy. Set `despine` to False. The middle I've would be harder and would probably require you to change some code yourself.

**Comment by kennethdistefano** [comment]
Thank you!!
I think I did it correctly. Within the `__init__()` definition I changed `despine` argument to False and it created this
![temp2](https://user-images.githubusercontent.com/65573427/84583815-baf37700-adc2-11ea-9a87-c72bd560e9a5.png)

Lastly, in order to add ticks, should I read more into GridSpec (because I've never used it until today) or try and edit "brokenaxes.py"?

**Comment by bendichter** [comment]
```python
from brokenaxes import brokenaxes
from matplotlib.gridspec import GridSpec

sps1, sps2, sps3 = GridSpec(3,1)

samples = np.linspace(0,100,1000)
y = np.sin(samples)

bax1 = brokenaxes(ylims=((-1, .3),(.7, 1)), subplot_spec=sps1)
bax1.plot(samples, y, '.')
bax2 = brokenaxes(ylims=((-1, .3),(.7, 1)), subplot_spec=sps2)
bax3 = brokenaxes(ylims=((-1, .3),(.7, 1)), subplot_spec=sps3)
```

you can use `bax.ax` to adjust the properties of any of the individual panels within the subplot.

**Comment by kennethdistefano** [comment]
Okay thank you.
I am unsure what "`bax.ax`" is referring to, however, I created ticks with `bax.tick_params()`.

```
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
import numpy as np
from brokenaxes import brokenaxes

#constants
XMIN=0
XMAX=10
YMIN=-1.25
YMAX=50.25
YBREAK_START=1.1
YBREAK_END=49.5

# data
x = np.linspace(XMIN,XMAX)
y1=np.sin(x)
y2=np.cos(x)
y3=y1*y2

# make outlier
y3[23] += 50

# organize b/c for-loop
ydata = [y1, y2, y3]

# set up figure and axes
fig = plt.figure()
gs = GridSpec(nrows=3, ncols=1, hspace=0, figure=fig)

# plot data with break in axes
for num, item in enumerate(gs):
  bax = brokenaxes(ylims=((YMIN, YBREAK_START), (YBREAK_END, YMAX)), 
                    subplot_spec=item)
  bax.plot(x, ydata[num], 'x')
  bax.tick_params(axis='x', top=True, direction='in')

plt.show()

```
![temp3](https://user-images.githubusercontent.com/65573427/84799320-bb0d9580-afc1-11ea-9b25-b33c589357f7.png)
I included my code and the plot it creates for completeness and to make sure we are on the same page.

Finally, this is super nit-picky, but within `bax.tick_params(axis='x', top=True, direction='in')` above, the `top=True` argument appears to be ignored. I believe this occurs because the top ticks are being covered up. Would there be way around this?

I apologize for dragging this on, however, I really appreciate your help thus far.

**Comment by kennethdistefano** [comment]
Hello, by looking at #17, I managed to create my nit-picky tick marks!

![temp4](https://user-images.githubusercontent.com/65573427/84808669-a4217000-afce-11ea-811f-5bbf484e9676.png)

So, by editing my for-loop to:
```
# plot data with break in axes
for num, item in enumerate(gs):
  bax = brokenaxes(ylims=((YMIN, YBREAK_START), (YBREAK_END, YMAX)), 
                    subplot_spec=item)
  bax.plot(x, ydata[num], 'x')
  bax.tick_params(axis='x', direction='in')
  bax.axs[0].xaxis.set_ticks_position('top')
  bax.axs[0].xaxis.set_ticklabels([])
```
I was able to manipulate the `bax.ax[0]` axis, (I did not realized it was indexed - oof).

Thank you for all of your help!

**Comment by bendichter** [comment]
@kennethdistefano no problem! Good to close?
