### ISSUE TITLE
Formatting axes for pgf rendering in LaTeX

### ISSUE THREAD

**Issue by kanginthaya** [bendichter/brokenaxes#51]
Thank you for the great package! It has been very useful to me. I noticed a small bug in your code related to using pgf rendering for LaTeX. Below is a small example:

```
import matplotlib.pyplot as plt
import numpy as np
import matplotlib as mpl
import os
from brokenaxes import brokenaxes
import matplotlib.ticker

samples = np.linspace(0,1000,4001)
y = np.sin(samples)
bax = brokenaxes(xlims=((0, 20),(81, 100)))
bax.plot(samples,y, color='k',ls='-')
bax.grid(linestyle='dotted', alpha=0.5)

plt.savefig('sample.pgf', format='pgf', bbox_inches='tight')
```

When I use this generated pgf plot in my LaTeX document, the axes tick labels still appear in the default TeX font, whereas in principle it should adapt to the native font specified in LaTeX. A possible way to solve this is to add the following lines (in general).

```
fmt = matplotlib.ticker.StrMethodFormatter("{x:g}")
ax.xaxis.set_major_formatter(fmt)
ax.yaxis.set_major_formatter(fmt)
```
But if I modify the last two lines when using brokenaxes as,
```
fmt = matplotlib.ticker.StrMethodFormatter("{x:g}")
bax.xaxis.set_major_formatter(fmt)
bax.yaxis.set_major_formatter(fmt)
```
then I get the error  - 
`AttributeError: 'CallCurator' object has no attribute 'set_major_formatter'`

Instead, I found that adding the above three lines inside the **for ax in self.axs** loop in the function **standardize_ticks(self, xbase=None, ybase=None)** solves the problem.

```
for ax in self.axs:
    if ax.is_first_col():
        if ax.yaxis.get_scale() == 'log':
            ax.yaxis.set_major_locator(ticker.LogLocator(ybase))
        else:
            ax.yaxis.set_major_locator(ticker.MultipleLocator(ybase))
    if ax.is_last_row():
        if ax.xaxis.get_scale() == 'log':
            ax.xaxis.set_major_locator(ticker.LogLocator(xbase))
        else:
            ax.xaxis.set_major_locator(ticker.MultipleLocator(xbase))
            
    fmt = ticker.StrMethodFormatter("{x:g}")
    ax.xaxis.set_major_formatter(fmt)
    ax.yaxis.set_major_formatter(fmt)
```

I am not sure if this is the best way to change the code. May be its better to add an if statement to check whether the user wants to use pgf rendering.

**Comment by bendichter** [comment]
@kanginthaya thanks for the great report, with minimal example and a fix! For now, I would recommend simply doing this:

```python
import matplotlib.pyplot as plt
import numpy as np
import matplotlib as mpl
import os
from brokenaxes import brokenaxes
import matplotlib.ticker

samples = np.linspace(0,1000,4001)
y = np.sin(samples)
bax = brokenaxes(xlims=((0, 20),(81, 100)))
bax.plot(samples,y, color='k',ls='-')
bax.grid(linestyle='dotted', alpha=0.5)

plt.savefig('sample.pgf', format='pgf', bbox_inches='tight')

for ax in bax.axs:
    fmt = matplotlib.ticker.StrMethodFormatter("{x:g}")
    ax.xaxis.set_major_formatter(fmt)
    ax.yaxis.set_major_formatter(fmt)
```

I'm not familiar with the `StrMethodFormatter` command so I don't know if it would mess up any other use-cases. I think the above fix should be simple enough for the relatively tech-savvy users who are already using latex. If this issue keeps on coming up, I'll look into incorporating these lines into the package.
