### ISSUE TITLE
What license is this package distributed under?

### ISSUE THREAD

**Issue by duncanmmacleod** [bendichter/brokenaxes#56]
@bendichter, I've just discovered `brokenaxes`, and it does its job very well, thanks for maintaining it!

I am, however, confused about the license; the `setup.py` states the license as MIT, but the `LICENSE` file itself is BSD-3-Clause. Can you clarify which one is correct?

**Comment by bendichter** [comment]
Hmmm You are right that is a discrepancy, but it shouldn't matter for most
users. Which I've would be more convenient for you?

**Comment by duncanmmacleod** [comment]
It doesn't make any difference to me, but I am trying to package up this project for distribution as a conda package, and need to know what license to carry forward.

**Comment by bendichter** [comment]
changed to MIT

**Comment by bendichter** [comment]
@duncanmmacleod you're now a contributor ;-). Feel free to distribute as a conda package. Is there a way to make me a maintainer?

**Comment by duncanmmacleod** [comment]
Yes, I will include your name (actually your github handle) in the recipe when I publish it.
