### ISSUE TITLE
[Feature request] Zoom effect with Matplotlib

### ISSUE THREAD

**Issue by JanWaldhorn** [bendichter/brokenaxes#59]
Thanks for the nice implementation of the broken axes.

I would like to zoom out a small section in another subplot (see picture).

![example](https://user-images.githubusercontent.com/57268762/104473895-bf347c80-55bd-11eb-84c3-ef541f9568f5.png)

With matplotlib there is a corresponding "hack" (see [here](https://matplotlib.org/3.1.3/gallery/subplots_axes_and_figures/axes_zoom_effect.html)) which however requires the normal matplotlib instance.

The current error code in the combination of brokenaxes and this zoom feature is for me e.g.
`'transform' must be an instance of matplotlib.transforms.Transform, not a brokenaxes.CallCurator
`

Would there be a way to feed the modifiactions of brokenaxes back into a matplotlib object?

**Comment by bendichter** [comment]
Is this what you are looking for?

![image](https://user-images.githubusercontent.com/844306/104483138-c9428500-5595-11eb-9cc0-97d3ccab49c9.png)


```python
fig = plt.figure(figsize=(5, 5))

sps_bax = GridSpec(2,1)[1]

bax = brokenaxes(xlims=((0,1.5), (1.6,5)), subplot_spec=sps_bax)
ax1 = plt.subplot(221)
ax1.set_xlim(0, 1)
zoom_effect01(ax1, bax.axs[0], 0.2, 0.8)

ax1 = plt.subplot(222)
ax1.set_xlim(2, 3)
zoom_effect02(ax1, bax.axs[1])

plt.show()
```

**Comment by JanWaldhorn** [comment]
Astonishing. Grandiose. Exactly that. Thanks a lot 👍
