### ISSUE TITLE
How to modify the ticks on BrokenAxes

### ISSUE THREAD

**Issue by Solacex** [bendichter/brokenaxes#61]
![image](https://user-images.githubusercontent.com/12868455/111265565-66e13000-867d-11eb-80b0-961b28952425.png)

I am trying to modify the x-ticks in the above subplot but failed. 

I want to change the x-ticks from [5,19,15...40] to [4,8,12...40]
But get: 
![image](https://user-images.githubusercontent.com/12868455/111265744-ad368f00-867d-11eb-9a71-36926e3f0c18.png)

**Comment by bendichter** [comment]
Could you please upload a minimal example of code that reproduces this issue?

**Comment by Solacex** [comment]
Hello, this problem has been solved, thanks for your response.

**Comment by ZhouWenjun2019** [comment]
> Hello, this problem has been solved, thanks for your response.

How to solve this problem ? I also meet it.
