### ISSUE TITLE
Adding y-label removes x-label

### ISSUE THREAD

**Issue by bastorer** [bendichter/brokenaxes#65]
Adding a y-label seems to remove the x-label. That is, calling `set_ylabel` before `set_xlabel` is fine, but calling `set_ylabel` after `set_xlabel` removes the x-label (sample code included below).

This seems to be the case with and without the log-y scale and with and without specifying the gridspec parameters.

Specifying the y-label first is a functioning work-around, but I thought I'd mention this in case there's a known solution.

All told, an incredibly helpful package! I especially appreciate the warning in the README about being careful when using broken axes :-)

```
import numpy as np
import matplotlib.pyplot as plt
from brokenaxes import brokenaxes

gridspec =  dict( left = 0.15, bottom = 0.2, top = 0.95, right = 0.97 )

fig = plt.figure(figsize=(5, 2.5))
ax = brokenaxes( xlims = ((-5, 1), (1.2, 5)), ylims = ((1e-4, 1e0),), wspace=.05, yscale = 'log', **gridspec )

x = np.linspace( -5, 5, 100 )
y = np.exp( -x**2 )

ax.plot( x, y )

if True:
    # This prints both labels
    ax.set_ylabel('Y')
    ax.set_xlabel('X', labelpad = 5)
else:
    # This only puts the Y label
    ax.set_xlabel('X', labelpad = 5)
    ax.set_ylabel('Y')

ax.set_yscale('log')

plt.savefig('test.pdf')
```

**Comment by bendichter** [comment]
I can't reproduce and I don't see anything in the code that would cause this. Mind trying on another machine?

**Comment by bastorer** [comment]
I didn't see anything in the code that would cause it either [ although I only did a cursory skimming ]. I've tested on two machines, and both produced the odd behaviour. In case it helps, the I've listed my python and matplotlib versions below.

Machine 1: Python version 3.7.9, Matplotlib version 3.3.3
Machine 2: Python version 3.7.4, Matplotlib version 3.1.1

**Comment by Marti-R** [comment]
Hey, I don't know if this is still needed, but I met a very similar issue and wanted to add to this topic:
I was unable to reproduce the issue @bastorer had, but I noticed that calling `set_ylabel` after `set_xlabel` shifts the xlabel downwards.

```
from matplotlib import gridspec
from brokenaxes import brokenaxes
import matplotlib.pyplot as plt

fig = plt.figure()
grid_spec = gridspec.GridSpec(1, 3, width_ratios=[1, 1, 1])

ax0 = brokenaxes(subplot_spec=grid_spec[0], despine=False)
ax1 = brokenaxes(subplot_spec=grid_spec[1], despine=False)
ax2 = brokenaxes(subplot_spec=grid_spec[2], despine=False)

ax0.set_xlabel("xlabel")

ax1.set_ylabel("ylabel")
ax1.set_xlabel("xlabel")

ax2.set_xlabel("xlabel")
ax2.set_ylabel("ylabel")

plt.show()
```

![example_brokenaxes](https://user-images.githubusercontent.com/56543191/130368170-6302a2af-be7a-47df-90d0-ecc420d49674.png)

Compare this to the behavior with regular axes:

```
from matplotlib import gridspec
from brokenaxes import brokenaxes
import matplotlib.pyplot as plt

fig = plt.figure()
grid_spec = gridspec.GridSpec(1, 3, width_ratios=[1, 1, 1])

ax0 = fig.add_subplot(grid_spec[0])
ax1 = fig.add_subplot(grid_spec[1])
ax2 = fig.add_subplot(grid_spec[2])

ax0.set_xlabel("xlabel")

ax1.set_ylabel("ylabel")
ax1.set_xlabel("xlabel")

ax2.set_xlabel("xlabel")
ax2.set_ylabel("ylabel")

plt.show()
```

![example_plt](https://user-images.githubusercontent.com/56543191/130368200-3efe4c74-b90f-449e-8433-c0e44dbdfed8.png)

I hope this can maybe help finding the issue.
BTW Thanks for the helpful package!
