### ISSUE TITLE
Trouble getting ticks on the top and right spine

### ISSUE THREAD

**Issue by DVads** [bendichter/brokenaxes#66]
I have been struggling with this for a while, looked all over the place, but I hope this isn't easily available information that I just missed. I have been using brokenaxes and love the look, but the problem has been getting the ticks and the tick labels on the right axis and the top. Minimum working example at the bottom. I am not the most experienced python coder yet, so I appreciate the help.

```
import matplotlib.pyplot as plt
import numpy as np
from brokenaxes import brokenaxes
fig = plt.figure()

x,y1,y2 = [150,200,240],[5.68, 5.69, 5.72],[4.02,3.98,4.00]

bax = brokenaxes(ylims=((3.968,4.025),(5.675,5.734)), hspace=.15, despine=False)

bax.plot(x,y1,marker='s')
bax.plot(x,y2,marker='d')

bax.tick_params(axis = 'both', labelsize=16, length=6, width=2, direction='in')


bax.set_xlim([150,245])

fig = plt.gcf()
```

This is how my plot looks

![Example_graph](https://user-images.githubusercontent.com/85943057/122058789-46e01a80-cdec-11eb-9eea-16d5f355bd1c.PNG)

And this is how I want my plot to look (pardon the crude paint job)

![Example_graph2](https://user-images.githubusercontent.com/85943057/122059766-43995e80-cded-11eb-9aa7-b4e8d09da38b.png)

**Comment by bendichter** [comment]
@DVads thanks for the well written issue

```python
import matplotlib.pyplot as plt
import numpy as np
from brokenaxes import brokenaxes
fig = plt.figure()

x,y1,y2 = [150,200,240],[5.68, 5.69, 5.72],[4.02,3.98,4.00]

bax = brokenaxes(ylims=((3.968,4.025),(5.675,5.734)), hspace=.15, despine=False)

bax.plot(x,y1,marker='s')
bax.plot(x,y2,marker='d')

bax.tick_params(axis = 'both', labelsize=16, length=6, width=2, direction='in')


bax.set_xlim([150,245])

for ax in bax.axs:
    subplot_spec = ax.get_subplotspec()
    if  subplot_spec.is_first_row():
        if subplot_spec.is_last_row():
            ax.xaxis.set_ticks_position('both')
        else:
            ax.xaxis.set_ticks_position('top')
    if subplot_spec.is_last_col():
        if subplot_spec.is_first_col():
            ax.yaxis.set_ticks_position('both')
        else:
            ax.yaxis.set_ticks_position('right')
```

**Comment by DVads** [comment]
Thanks for the help, but I still get some error messages when trying to run this

![Code_error](https://user-images.githubusercontent.com/85943057/122182192-5877ff80-ce8a-11eb-999c-efaa6d6800b8.PNG)

Am I missing something in the start of the code? something I haven't imported?

**Comment by bendichter** [comment]
I think that's a matplotlib version issue. This should work for you:

```python
import matplotlib.pyplot as plt
import numpy as np
from brokenaxes import brokenaxes
fig = plt.figure()

x,y1,y2 = [150,200,240],[5.68, 5.69, 5.72],[4.02,3.98,4.00]

bax = brokenaxes(ylims=((3.968,4.025),(5.675,5.734)), hspace=.15, despine=False)

bax.plot(x,y1,marker='s')
bax.plot(x,y2,marker='d')

bax.tick_params(axis = 'both', labelsize=16, length=6, width=2, direction='in')


bax.set_xlim([150,245])

for ax in bax.axs:
    if  ax.is_first_row():
        if ax.is_last_row():
            ax.xaxis.set_ticks_position('both')
        else:
            ax.xaxis.set_ticks_position('top')
    if ax.is_last_col():
        if ax.is_first_col():
            ax.yaxis.set_ticks_position('both')
        else:
            ax.yaxis.set_ticks_position('right')
```

but when you update matplotlib you'll need the first version I gave

**Comment by DVads** [comment]
It seems to work ok for my "minimum working example", using the code for the old matplotlib version. I couldn't get the numbers to appear, but the ticks came at least. Thanks a lot for the help!

I couldn't get it to work for my actual plot, but that plot is pretty messy and is certainly not the most elegant code. I am still learning, but this has pushed me further along the way. I will mark it as closed for now, while trying to wrestle my code a bit more. Hopefully the next time I will make a better code from the ground up!

**Comment by DVads** [comment]
I use the anaconda platform and managed to update matplotlib to version 3.3.4, but the new spec of code still doesn't work as intended. Still gives me the 'SubplotSpec' object has no attribute 'is_first_row' error message. But I will work on that a little bit, thanks for the help I will try a bit more by myself now, unless you have some parting advice. Thank you for your time!
