### ISSUE TITLE
text and annotate ignores brokenaxes limits

### ISSUE THREAD

**Issue by EKukstas** [bendichter/brokenaxes#68]
I want to annotate my plots with strings but both 'text' and 'annotate' ignore the axis limits set by brokenaxes. Using one of the examples:

```
fig = plt.figure(figsize=(5, 2))
bax = brokenaxes(xlims=((0, .1), (.4, .7)), hspace=.05)
x = np.linspace(0, 1, 100)
bax.plot(x, np.sin(10 * x), label='sin')
bax.plot(x, np.cos(10 * x), label='cos')
bax.legend(loc=3)
bax.set_xlabel('time')
bax.set_ylabel('value')
bax.text(0.5, 0.8, '0', rotation=90, color='C3', fontsize=12)
```

I get the following:
![brokenaxes_annotate_issue](https://user-images.githubusercontent.com/30339507/124752830-408f1b00-df20-11eb-913b-3a5fbba573b3.jpeg)

I feel like it's a simple enough fix but can't figure out what I need to change in order to suppress the second annotation being plotted. Can anyone point me in the right direction?

**Comment by bendichter** [comment]
just a minor adjustment on the last line:

```python
import matplotlib.pyplot as plt
from brokenaxes import brokenaxes
import numpy as np

fig = plt.figure(figsize=(5, 2))
bax = brokenaxes(xlims=((0, .1), (.4, .7)), hspace=.05)
x = np.linspace(0, 1, 100)
bax.plot(x, np.sin(10 * x), label='sin')
bax.plot(x, np.cos(10 * x), label='cos')
bax.legend(loc=3)
bax.set_xlabel('time')
bax.set_ylabel('value')
bax.big_ax.text(0.5, 0.8, '0', rotation=90, color='C3', fontsize=12)
```

**Comment by bendichter** [comment]
well... that sort of works. I think it's using [0,1], [0,1] as the coordinate space. I'll see if I can fix that

**Comment by Thomas-Moore-Creative** [comment]
First - thank you for coding and sharing `brokenaxes` !!!

> well... that sort of works. I think it's using [0,1], [0,1] as the coordinate space. I'll see if I can fix that

I'm placing text labels and would like to use the actual coordinate values ( as I used to ).  At the moment it is an iterative guessing approach across [0,1] range which makes it harder to generalise ( for me ).  Any progress on your comment above?

**Comment by bendichter** [comment]
Hi @Thomas-Moore-Creative No problem, it's fun to see all the cool uses!

really? This appears to be working as you want for me:

```python
import matplotlib.pyplot as plt
from brokenaxes import brokenaxes
import numpy as np

fig = plt.figure(figsize=(5, 2))
bax = brokenaxes(xlims=((0, .01), (.04, .07)), hspace=.05)
x = np.linspace(0, .1, 100)
bax.plot(x, np.sin(100 * x), label='sin')
bax.plot(x, np.cos(100 * x), label='cos')
bax.legend(loc=3)
bax.set_xlabel('time')
bax.set_ylabel('value')

bax.text(0.045, 0.5, '0', fontsize=12)
```

![image](https://github.com/bendichter/brokenaxes/assets/844306/2ce45830-1ec8-41a3-9f1c-9f5e13c9eae5)

this would not work if the underlying axes were [0,1],[0,1].

**Comment by bendichter** [comment]
Note that I am using bax.text, not bax.big_ax.text as I did in the example above
