### ISSUE TITLE
Correct gapped line plotting 

### ISSUE THREAD

**Issue by sbolushevsky** [bendichter/brokenaxes#69]
Do you consider to fix the gapped line plotting? 
The correct way to plot the parts of a broken line is that they should point to each other (like in picture attached).
Thank you   

![image](https://user-images.githubusercontent.com/65050575/126580756-70591b51-145b-4210-8be9-38a7fd9c7eba.png)

**Comment by bendichter** [comment]
I disagree. I don't think the lines should point to each other, I think they should follow their axes until the split and be disjoint, not pointing to each other, as the package currently does.

**Comment by sbolushevsky** [comment]
Well.. graphpad's developers of prism would disagree with you 
Will stick with their app then
