### ISSUE TITLE
Manually scales axes option?

### ISSUE THREAD

**Issue by zyang1988** [bendichter/brokenaxes#7]
I really like this small gadget. 

May I ask is there an option to scale the axes for the two portions of the axes manually after breaking? For example, for an axis with a range of 0-10 and 100-1000 after breaking, is it possible to place the break mark in the middle of the axis so that the data between 0-10 and 100-1000 can be separately plotted in each of the 50% of the panel? Thanks.

**Comment by bendichter** [comment]
I'm glad you find it useful! I did not build that in, but it should not be too hard to do... let me try something

**Comment by zyang1988** [comment]
The broken axis example on matplotlib does not work for plotting multiple data sets in one plot. That's why I like this small tool. I think it is gonna make this tool even more useful by adding the 'manual scale axis' function. In this case, one can emphasis one of the two portions after the axis breaking,

**Comment by bendichter** [comment]
I don't think I want to move in that direction at this point, but you can fork my repo and make whatever changes you want. To plot multiple datasets on broken axes I would do:

```
fig, axs = plt.subplots(1,2)
for ax in axs:
    ax.plot(x1, y1)
    ax.plot(x2, y2) #or ax.hist or ax.imagesc or whatever 
axs[0].set_xlim((0,10))
axs[1].set_xlim((10,100))
```
