### ISSUE TITLE
Work with Seaborn?

### ISSUE THREAD

**Issue by RuihongQiu** [bendichter/brokenaxes#70]
Thank you for the great repo!

I was originally using Seaborn for the figure style.
Is it possible to use brokenaxes with the seaborn.lineplot, which draws multiple curves at the same time for my data?

**Comment by bendichter** [comment]
@RuihongQiu 

If you want multiple lines on the same plot, you can use

```python
bax = brokenaxes(...)
bax.plot(x1, y1)
bax.plot(x2, y2)
```

Does that work for you?

**Comment by RuihongQiu** [comment]
Thank you for the prompt reply.

Yea, that's what it meant to be. But I want to use the same palette as other figures.

With Seaborn I write something like:
```python
seaborn.lineplot(x='lambda', y='metric', hue='dataset', data=data, legend='full', markers=True, style=dataset)
```
which is using quite a few Seaborn default setting as the other figures.

I think to separate the drawing of all the curves and to set the style to be consistent with other figures is a little bit too complicated.

So I wonder if there is a way to use brokenaxes and Seaborn together.

Thank you again.

**Comment by bendichter** [comment]
Does `seaborn.set_style("whitegrid")` do what you mean?

**Comment by bendichter** [comment]
We don't have the ability to automatically extract and format data directly from a pandas dataframe, and that is unfortunately outside the scope of this package. You'd have to do that yourself.

**Comment by RuihongQiu** [comment]
Ah alright. And I will have a try to use the default method provided by `matplotlib`.

A big thank you for the advice.
