### ISSUE TITLE
Matplotlib deprecation warning `ax.is_first_col`

### ISSUE THREAD

**Issue by Knusper** [bendichter/brokenaxes#73]
I just updated my matplotlib installation to 3.4.2 and now I get from this package some warnings:
```
 if ax.is_first_col():
/home/ehere/miniconda3/envs/astroconda/lib/python3.7/site-packages/brokenaxes.py:180: MatplotlibDeprecationWarning: 
The is_first_row function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use ax.get_subplotspec().is_first_row() instead.
```

**Comment by bendichter** [comment]
Thanks for the repost, @Knusper. I have fixed in dev but haven't pushed a release. Looks like it is time to do so

**Comment by bendichter** [comment]
@Knusper ok, I issued a new release. Please uninstall, reinstall, and open again if this problem persists.
