### ISSUE TITLE
Strange label and grid behaviour when using subplots

### ISSUE THREAD

**Issue by JoshuaKahn** [bendichter/brokenaxes#76]
I'm trying to make a subplot with two graphs that use the same set of broken axes. I have a few places I'd like to break (due to the data being time series, with gaps in time), so I use a function to generate breaks in time from a list of list to create a tuple of tuples.

When I try to use this in a subplot configuration, however, I run into two annoying issues. The first is that I can't get the subtitles and x-axis labels to stop interfering with each other. I'd usually use `tight_layout()` for this, but it doesn't entirely support `brokenaxes` yet (through testing, it causes labels to get cut off.) I tried using the code [here](https://github.com/bendichter/brokenaxes/issues/20#issuecomment-443299507) to fix it, but it seems that `GridLayout` doesn't like `bottom` or `left, with the error report being:
```
File "/home/username/.local/lib/python3.8/site-packages/brokenaxes.py", line 118, in __init__
    gs = gridspec.GridSpecFromSubplotSpec(
TypeError: __init__() got an unexpected keyword argument 'bottom'
```

Additionally, for some reason, a part of one of the subplots has a different grid size, as well as a different axis label set (a 50 sitting next to the parts of the subplot which I didn't specify). I don't know what is causing this and I can't find the option to stop it.

Here's an example image of what everything is looking like:

![example](https://user-images.githubusercontent.com/35244044/131974497-69af9871-37ed-4e3e-a747-1d7eb7a5144b.png)

The 'time' x axis label in the top graph is being cut off. The line in the middle of the data which has overlapping dates is actually a very small data set - I have plotted another (non-subplot) set of data with it being present, and have not seen the same issue.

Here's what my code looks like:

```

        values1 = [...]
        values2 = [...]

        time = [...]

        subplot1, subplot2 = GridSpec(2, 1)

        example_fig = plt.figure()
        example_fig.suptitle("Example Title")

        plot1 = BrokenAxes(
            fig=example_fig,
            xlims=self.get_sorted_tuple_of_tuples_of_time_list(),
            tilt=45.0,
            d=0.005,
            subplot_spec=subplot1,
        )
        plot2 = BrokenAxes(
            fig=example_fig,
            xlims=self.get_sorted_tuple_of_tuples_of_time_list(),
            tilt=45.0,
            d=0.005,
            subplot_spec=subplot2,
        )

        plot1.plot(time, values1)
        plot1.set_title("Values 1")
        plot1.set_ylabel("Value 1")

        plot2.plot(time, values2)
        plot2.set_title("Values 2")
        plot2.set_ylabel("Values 2")

        for plot in [plot1, plot2]:
            plot.set_xlabel("Time", 50)
            plot.grid()

            for ax in plot.axs:
                ax.xaxis.set_major_locator(dates.MinuteLocator(interval=30))
                ax.tick_params(axis="x", labelrotation=90)

        example_fig.set_size_inches(18.5, 10.5)
        plt.savefig(file_path + "example.png", dpi=300)
```

**Comment by bendichter** [comment]
@JoshuaKahn sorry I missed this. I would remove the x tick labels of the upper plot entirely. Something like

```python
for ax in plot1.axs:
    ax.set_xticks([])
```

You can also adjust the "labelpad" of the xlabel:

```python
plto1.set_xlabel('Time', labelpad=10)
```

though I would remove this as well, since it is clear from the bottom x axis label.

Finally, you can adjust the space between the plots with a vspace arg:

```python
gs = gridspec.GridSpecFromSubplotSpec(..., vspace=10)
```

I'm going to close this for now. Feel free to reopen if you are still dealing with this and these solutions don't work for you.
