### ISSUE TITLE
Allow array input for xlims/ylims

### ISSUE THREAD

**Issue by ThomasHilger** [bendichter/brokenaxes#77]
When passing an array (shape (x,2)) to xlims, an exception is raised (ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()) occurs, although the subsequent code should behave just fine.
https://github.com/bendichter/brokenaxes/blob/bfb0a7c42c49e86c317d183686ac77d8af64f344/brokenaxes.py#L82

Isn't it better to just write:
if xlims is not None:...
Then everything should work fine, and it is not necessary to cast the array to a list.

**Comment by bendichter** [comment]
Yes this is a good idea. I'd be happy to review a PR
