### ISSUE TITLE
`AttributeError: 'SubplotSpec' object has no attribute 'is_last_row'` when running the first example

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [bendichter/brokenaxes#79]
I try with `0.2.0` and the lastest `0.5.0` to run the very first example in README. Both cases throw me the same error:
`AttributeError: 'SubplotSpec' object has no attribute 'is_last_row' `

The call stack is shown in this screenshot.
![image](https://user-images.githubusercontent.com/28505034/143973785-84c5b7f6-ebb0-43d0-aad8-19878819c077.png)

**Comment by bendichter** [comment]
@cakebytheoceanLuo Try upgrading matplotlib:

```pip install -U matplotlib```

**Comment by cakebytheoceanLuo** [comment]
Hi @bendichter Thank you!
![image](https://user-images.githubusercontent.com/28505034/144381828-6d6eced5-7a02-4113-bdca-d7a105b4e92b.png)

**Comment by jvavrek** [comment]
I'm running into this despite having a new matplotlib version:
```
matplotlib        3.7.2
brokenaxes        0.4.2
```
