### ISSUE TITLE
datetime xaxis

### ISSUE THREAD

**Issue by JLeftley** [bendichter/brokenaxes#8]
It would be very useful if this could work with datetime axes as date based data often has large empty gaps. Currently I receive the warning: unsupported operand type(s) for +: 'int' and 'datetime.timedelta' when setting brokenaxes(xlims=((a,b),(c,d))) where a,b,c and d are datetime.datetime values.

Cheers,

Line of code responsible for error:
`from brokenaxes import brokenaxes`
`import datetime`
`bax=brokenaxes(xlims=((datetime.datetime(2008,1,1), datetime.datetime(2012,1,1)),(datetime.datetime(2014,1,1), datetime.datetime(2017,1,1))))`

**Comment by bendichter** [comment]
I agree, this would be a great feature! Let me see if I can figure out what's going on here.

**Comment by bendichter** [comment]
done!

If you are using datetimes for ticks you will probably want to call `plt.gcf().autofmt_xdate()` as well, which messes up the diag placements, so I added two lines to fix that for you.

```python
from brokenaxes import brokenaxes
from datetime import datetime
import matplotlib.pyplot as plt

bax=brokenaxes(xlims=((datetime(2008,1,1), datetime(2012,1,1)),
                      (datetime(2014,1,1), datetime(2017,1,1))),
              ylims=((1,2),(4,5)))
plt.gcf().autofmt_xdate()

# fix diag markers
[dh.remove() for dh in bax.diag_handles]
bax.draw_diags()
```

**Comment by JLeftley** [comment]
Great, thanks!

**Comment by lgonzalezsa** [comment]
Hi All,
I know already closed but having same need to do just x axis break and following the fix diag marker not helping me. The difference is I am using pandas.plot()
`
ax = df[
    (
        (df['Class'].isin(['B-SMALL', 'SMALL']))
        & (df['Model']=='A')
    )
].groupby([
    'Model',
    'Date',
    'Class',
    'Flag'
])['50%'].median().unstack(['Model', 'Flag', 'Class']).plot(figsize=(16, 8), marker='o', linestyle='')
bax = brokenaxes(xlims=(
    (dt.datetime(2018,6,1), dt.datetime(2018,7,30)),
    (dt.datetime(2019,2,15), dt.datetime(2019,5,10))))
plt.gcf().autofmt_xdate()
[dh.remove() for dh in bax.diag_handles]
bax.draw_diags()
`

Here the before and after:
![image](https://user-images.githubusercontent.com/704686/57257449-a7e67300-7016-11e9-93a9-18c9f416c272.png)

Any help more than welcome!

**Comment by bendichter** [comment]
`df.plot` is a great tool, but we do not support it. You'll need to call `plot` from the `bax` object.
