### ISSUE TITLE
duplicated offset text on using scientific notation

### ISSUE THREAD

**Issue by iTomxy** [bendichter/brokenaxes#82]
- version: brokenaxes 0.5.0

When using scientific notations:
```python
import matplotlib.pyplot as plt 
from brokenaxes import brokenaxes 
import numpy as np 

fig = plt.figure(figsize=(6,4))
baxes = brokenaxes(ylims=((0,30000),(75000,85000)), hspace=.1, despine=False)

X = np.sort(np.array([3,-1,0,4,5,-2,7]))
Y = np.array([80000,10000,5000,3000,1000,500,100])
Z = np.array([800,1000,1200,3000,10000,30000,15000])

baxes.plot(X,Y,label="squared")
baxes.plot(X,Z,label="cubed")

baxes.ticklabel_format(style='sci', scilimits=(-1,2), axis='y')  # here

baxes.legend(loc="best")
plt.plot()
plt.show()
```
it gives out **two** offset texts:
![Inkedclip_LI](https://user-images.githubusercontent.com/44149820/162632445-cdb83b88-095a-4c97-8487-1087123dfc3c.jpg)

**Comment by bendichter** [comment]
Hmm good catch. Let me think about how best to fix that. Maybe there's an exponent object we can delete?

**Comment by bendichter** [comment]
Maybe 

baxes.axs[1].get_yaxis().get_offset_text().set_visible(False)

**Comment by iTomxy** [comment]
It works ! thanks

**Comment by iTomxy** [comment]
Oh, this will fail if a `baxes.grid()` were called **after** it, but work if before.

**Comment by bendichter** [comment]
can you elaborate?
