### ISSUE TITLE
Vertical space between subplots

### ISSUE THREAD

**Issue by MTUNG311** [bendichter/brokenaxes#84]
I used tight_layout and draw_diags to adjust the vertical space between the graph 
plt.tight_layout()
    for bax in baxs:
        for handle in bax.diag_handles:
            handle.remove()
        bax.draw_diags()
but the graph became so small like this:
![image](https://user-images.githubusercontent.com/51476468/162860674-dfab96c2-6421-4c67-bbbf-eac23e6c118e.png)

**Comment by bendichter** [comment]
Yes, this package does not work well with `tight_layout`

**Comment by MTUNG311** [comment]
I see. When I disabled the tight_layout, the space between plots is so narrow that the bottom spines may overlap with the title of the next plot. And somehow the y axis tick label of the graph on the second column shows up. Is there a way to fix this and adjust the vertical space between graphs without using tight_layout?

![image](https://user-images.githubusercontent.com/51476468/163076604-6437fc0d-eb82-4359-8ac7-f071eef8b467.png)

**Comment by MTUNG311** [comment]
And also, is there a way to share one x axis for all subplots in the same column so that all subplots in that column will zoom if I zoom one of the them?

**Comment by bendichter** [comment]
You can adjust the position of the xlabels with the `labelpad` arg. https://github.com/bendichter/brokenaxes/blob/c65c20d753177e95578ea99ed819880141216924/brokenaxes.py#L333-L334

I'd probably also create more `vspace` with your `GridSpec` command so that your title doesn't overlap the axes above.

There is no way to share x axis. You'll have to do it manually.

**Comment by bendichter** [comment]
It looks like your issue is your figure window size. Do you need it to be that wide? It's possible to make the necessary adjustments if you need to, but if you could just change your figure width that would probably be the easiest.

**Comment by MTUNG311** [comment]
Yes, cuz in real practice, I may need to show data of multiple days instead of two days so I guess I should maximize the figure width. Anyways, I have created extra space between subplots with GridSpec and that solve the problems. Thank you for your replies!
