### ISSUE TITLE
Broken x and y axes - issue with log scale

### ISSUE THREAD

**Issue by Masoom02** [bendichter/brokenaxes#88]
Hi.. Thanks for the package. I am facing a few issues while using this package to produce my results. I need to plot in log scale both the x and y axes. Also, I need two separate ranges to be shown on both axes. However, when I specify the log scale, it is not giving me the desired result. Even when I explicitly mention the major and minor tics, the issue still persists.
The code I am using -

```python
from matplotlib.pyplot import figure
from brokenaxes import brokenaxes
from numpy import logspace
from pylab import *
from numpy import *
import os
from global_tools import *
from global_defs import *

x = logspace(-35, +1, 200)
y = logspace(-32, -3, 200)

fig = plt.figure(figsize=[9,9])
bax = brokenaxes(xlims=((1E-35, 1E-10), (1E-3, 10)),
                 ylims=((0.8E-32, 1E-24), (1E-6, 2e-3)),
                 xscale='log', yscale='log')

path = os.getcwd()+"/"

lst_limits3 = Read_Data_File(path+"a.txt")

lst_m3 = [ 10.**lst_limits3[0][j] for j in range(len(lst_limits3[0])) ]
lst_g_hi_20153 = [10.**lst_limits3[1][j] for j in range(len(lst_limits3[1]))]
bax.loglog(lst_m3, lst_g_hi_20153, color='#FF00FF', ls='dashed', lw=2.5, zorder=20)

lst_limits5 = Read_Data_File(path+"b.txt")
lst_m5 = [ 10.**lst_limits5[0][j] for j in range(len(lst_limits5[0])) ]
lst_g_hi_20155 = [10.**lst_limits5[1][j] for j in range(len(lst_limits5[1]))]
bax.loglog(lst_m5, lst_g_hi_20155, color='#b166d1', ls='dashed', lw=2.5, zorder=20)

bax.legend(loc=8)
bax.grid(axis='both', which='major', ls='-')
bax.set_xlabel('x')
bax.set_ylabel('y')
bax.grid(axis ='both', which='major', ls='-')
bax.grid(axis='both', which='minor', ls='--', alpha=0.4)
plt.show()

plt.close()

path = os.getcwd()+"/"
```

[a.txt](https://github.com/bendichter/brokenaxes/files/10124777/a.txt)

[b.txt](https://github.com/bendichter/brokenaxes/files/10124741/b.txt)
ichter/brokenaxes/files/
[outfile.pdf](https://github.com/bendichter/brokenaxes/files/10124757/outfile.pdf)
10124738/a.txt)

Thanks!

**Comment by bendichter** [comment]
The minor ticks and grid aren't showing up because your major tick labels are so far apart. If you had minor ticks and gridlines, it would look like this

![image](https://user-images.githubusercontent.com/844306/204852706-ee3bbca3-a202-49e7-a908-090b60d2260b.png)

**Comment by Masoom02** [comment]
Okay, great thanks. However, if you notice, the lower part of y-axis still does not have logscale ticks.
