### ISSUE TITLE
 AttributeError: 'SubplotSpec' object has no attribute 'is_last_row'

### ISSUE THREAD

**Issue by RMariaDelRioChanona** [bendichter/brokenaxes#92]
I am trying to use the python brokenaxes to break both x and y axis. I run the code suggested here https://www.codespeedy.com/create-a-plot-with-broken-axis-in-python-using-matplotlib/
```

import matplotlib.pyplot as plt 
from brokenaxes import brokenaxes 
import numpy as np 
fig = plt.figure(figsize=(6,4)) 
baxes = brokenaxes(xlims=((-2,3),(5,8)), ylims=((0,8),(9.5,21)), hspace=.1) 
X = np.array([3,-1,0,4,5,-2,7]) 
Y = x**2
Z = x**3
baxes.plot(X,Y,label="squared") 
baxes.plot(X,Z,label="cubed") 
baxes.legend(loc="best")
plt.plot()
plt.show()
```

However I get error:

`AttributeError: 'SubplotSpec' object has no attribute 'is_last_row'`

**Comment by bendichter** [comment]
@RMariaDelRioChanona for posterity, were you able to solve this by upgrading your matplotlib package?
