### ISSUE TITLE
is there any way to control the magnitude of the gap in x axis

### ISSUE THREAD

**Issue by yongqiang-zhao** [bendichter/brokenaxes#93]
Hi, is there any way to control the magnitude of the gap in x axis, similar with hspace does, but on the x axis?

**Comment by alpha-1-centauri** [comment]
Try to use wspace argument, e.g. wspace=0.01

**Comment by bendichter** [comment]
Yes, this is a common confusion. "hspace" means "height space" not "horizontal space". I don't like the terminology either, but I am keeping it for consistency with `GridSpec`.
