### ISSUE TITLE
Set minor xticks with brokenaxes

### ISSUE THREAD

**Issue by Wan-Sking** [bendichter/brokenaxes#94]
Thanks for brokenaxes it made the creation of this graphic much easier!

The only thing I still didn't manadge is to set minor xticks. Is there only one way or am I trying for nothing?
I've tested this and some variation, based on a previous post but it didn't work.

```ruby
plt.figure(figsize=(20, 12))
plt.rcParams.update({'font.size': 22,
                     'font.family': 'arial'})

bax = brokenaxes(xlims= ((-0.8, 80), (160, 180)), ylims= ((0, 180), (400, 420)), wspace= .07, hspace= .07)
for var in reactor:
    bax.plot(ExtDNA['Concentration ' + var].dropna(), c= color[reactor.index(var)], marker= marker[reactor.index(var)], ms= 10, linestyle= linestyle[reactor.index(var)], label= leg[reactor.index(var)])
bax.plot(417.1, c= 'r', marker= 'v', ms= 20, label= 'GH09 Inoculum')
bax.plot(19.2, c= 'sienna', marker= '*', ms= 20, label= 'BSG') 
bax.set_ylabel('Extracted DNA Concentration [ng'+r'$_{DNA}$'+'/µL'+r'$_{EB}]$', labelpad= 55)
bax.set_xlabel('Fermentation time [d]', labelpad= 35) 
bax.axs[0].set_xticks(list(np.arange(0,81,1)), labels= None, minor= True)
bax.axs[1].set_xticks(list(np.arange(160,181,1)), labels= None, minor= True)
bax.tick_params(axis= 'both', which= 'major', length= 6.0)
bax.tick_params(axis= 'x', which= 'minor', length= 4.0)

bax.legend(bbox_to_anchor= (1.007, 1.0125)) 
plt.show()
```
Any suggestion? Thanks in advance

**Comment by bendichter** [comment]
@Wan-Sking something like:

```python
plt.figure(figsize=(20, 12))
plt.rcParams.update({'font.size': 22,
                     'font.family': 'arial'})

bax = brokenaxes(xlims= ((-0.8, 80), (160, 180)), ylims= ((0, 180), (400, 420)), wspace= .07, hspace= .07)
for var in reactor:
    bax.plot(ExtDNA['Concentration ' + var].dropna(), c= color[reactor.index(var)], marker= marker[reactor.index(var)], ms= 10, linestyle= linestyle[reactor.index(var)], label= leg[reactor.index(var)])
bax.plot(417.1, c= 'r', marker= 'v', ms= 20, label= 'GH09 Inoculum')
bax.plot(19.2, c= 'sienna', marker= '*', ms= 20, label= 'BSG') 
bax.set_ylabel('Extracted DNA Concentration [ng'+r'$_{DNA}$'+'/µL'+r'$_{EB}]$', labelpad= 55)
bax.set_xlabel('Fermentation time [d]', labelpad= 35) 
bax.axs[0].set_xticks(list(np.arange(0,81,1)), labels= None, minor= True)
bax.axs[1].set_xticks(list(np.arange(160,181,1)), labels= None, minor= True)
for ax in bax.axs:
    ax.tick_params(axis= 'both', which= 'major', length= 6.0)
    ax.tick_params(axis= 'x', which= 'minor', length= 4.0)

bax.legend(bbox_to_anchor= (1.007, 1.0125)) 
plt.show()
```

**Comment by Wan-Sking** [comment]
Thanks for this quick response!

This solution succeeded at creating the minor ticks, however they are placed at the level of the y break (~400 Cf picture). if I remove the break on the y axis, then they're well placed. 

I've tested args variation but I've quickly run out of ideas...

![Extracted_test](https://github.com/bendichter/brokenaxes/assets/141162332/f85b229e-553c-47d4-bcd2-88a9e8a63b4b)

**Comment by bendichter** [comment]
I think the issue is with the spacing of the minor ticks

**Comment by Wan-Sking** [comment]
I've tried increasing the spacing (If I understand correctly what that means) but it doesn't solve the issue :(

It doesn't matter if it stays without minor ticks, it's more of a detail than anything.

Thanks for trying!

Wan

**Comment by Wan-Sking** [comment]
> @Wan-Sking something like:
> 
> ```python
> plt.figure(figsize=(20, 12))
> plt.rcParams.update({'font.size': 22,
>                      'font.family': 'arial'})
> 
> bax = brokenaxes(xlims= ((-0.8, 80), (160, 180)), ylims= ((0, 180), (400, 420)), wspace= .07, hspace= .07)
> for var in reactor:
>     bax.plot(ExtDNA['Concentration ' + var].dropna(), c= color[reactor.index(var)], marker= marker[reactor.index(var)], ms= 10, linestyle= linestyle[reactor.index(var)], label= leg[reactor.index(var)])
> bax.plot(417.1, c= 'r', marker= 'v', ms= 20, label= 'GH09 Inoculum')
> bax.plot(19.2, c= 'sienna', marker= '*', ms= 20, label= 'BSG') 
> bax.set_ylabel('Extracted DNA Concentration [ng'+r'$_{DNA}$'+'/µL'+r'$_{EB}]$', labelpad= 55)
> bax.set_xlabel('Fermentation time [d]', labelpad= 35) 
> bax.axs[0].set_xticks(list(np.arange(0,81,1)), labels= None, minor= True)
> bax.axs[1].set_xticks(list(np.arange(160,181,1)), labels= None, minor= True)
> for ax in bax.axs:
>     ax.tick_params(axis= 'both', which= 'major', length= 6.0)
>     ax.tick_params(axis= 'x', which= 'minor', length= 4.0)
> 
> bax.legend(bbox_to_anchor= (1.007, 1.0125)) 
> plt.show()
> ```

I tested your lastest solution but it didn't work either. But I tested new itterations of the quoted version and problem came from the incorrect selection of the subplots. 

 ```ruby
bax.axs[0].set_xticks(list(np.arange(0,81,1)), labels= None, minor= True)
bax.axs[1].set_xticks(list(np.arange(160,181,1)), labels= None, minor= True)
for ax in bax.axs:
    ax.tick_params(axis= 'both', which= 'major', length= 6.0)
    ax.tick_params(axis= 'both', which= 'minor', length= 4.0)
```

should become (here yticks have been added too)

```ruby
bax.axs[2].set_xticks(list(np.arange(0, 81, 2)), minor=True)
bax.axs[3].set_xticks(list(np.arange(160, 181, 2)), minor=True)
bax.axs[2].set_yticks(list(np.arange(10, 171, 20)), minor=True)
bax.axs[0].set_yticks(list(np.arange(410, 420, 20)), minor=True)
for ax in bax.axs:
    ax.tick_params(axis= 'both', which= 'major', length= 6.0)
    ax.tick_params(axis= 'both', which= 'minor', length= 4.0)
```
