### ISSUE TITLE
ax.set_xticks not recognised

### ISSUE THREAD

**Issue by carmennab** [bendichter/brokenaxes#97]
I'm trying to change the x-tick labels on my subplots

i've used ax.set_xlim() which has worked fine

but then when i use ax.set_xticks() and ax.set_xticklabels() the commands aren't recognised

I've tried putting them in different orders and in different sections of the script, but nothing seems to be working

### code below:

names = ['CTRL','BASE', '\u03B1 = 0.9', '\u03B1 = 0.6', 'LARM', 'CPOM', 'SM-LG', 'AWI']
sits = [ctrl, base, nine, six, larm, cpom, smlg, awi]
colors = ['blue','red','#e7298a','green','purple','#ff7f00','brown','black']
buoy_xs = [237,226,234]
buoy_ys = [147,153,135]

buoys = ['a','b','d']
buoy_names = ['BGEP-A','BGEP-B','BGEP-D']

fig = plt.figure(figsize=(15,15))
spec = gridspec.GridSpec(ncols=1, nrows=4, wspace=0.25, hspace=0.4)
days = np.arange(0,212)

ys = [0.865,0,0.46]
pads = [36,12,32,10]

for count, buoy in enumerate(buoys):
    
    bgep = np.asarray(Dataset('/Users/carmennab/Dropbox/met_office/data/validation/BGEP/'+buoy+
                              '_SIT_EASE_01Oct2016-30Apr2017.nc')['Sea Ice Thickness'])
    std = np.asarray(Dataset('/Users/carmennab/Dropbox/met_office/data/validation/BGEP/'+buoy+
                             '_SIT_EASE_01Oct2016-30Apr2017.nc')['Standard Deviation'])
    std[np.isnan(bgep)]=np.nan

    if count in [0,2]:
        xs = [0.133,0.172,0.211,0.25,0.289,0.328,0.367,0.406]
        ax = brokenaxes(ylims=((-3, 5.5), (19, 22)), hspace=0.2, subplot_spec=spec[count])
        for c, sit in enumerate(sits):
            s = sit[:,buoy_xs[count],buoy_ys[count]]
            ax.plot(days,(s-bgep)/std,label=names[c],color=colors[c])  
            ax.axhline(22,color='k')
            ax.axvline(212,color='k')
            diff = s - bgep
            error = np.round(np.nanmean(np.abs(diff)),2)
            fig.text(xs[c], ys[count], '%.2f' %error, ha='left',fontsize = 12,color=colors[c])
        
    else:
        xs = [0.01,0.06,0.11,0.16,0.21,0.26,0.31,0.36,0.41,0.46]
        ax = fig.add_subplot(spec[count])

        for c, sit in enumerate(sits):
            s = sit[:,buoy_xs[count],buoy_ys[count]]
            ax.plot(days,(s-bgep)/std,label=names[c],color=colors[c])
            ax.set_ylim(-3,3)
            diff = s - bgep
            error = np.round(np.nanmean(np.abs(diff)),2)
            ax.text(xs[c], 0.9, '%.2f' %error, ha='left',fontsize = 12,color=colors[c],transform = ax.transAxes)

    ax.fill_between(days,std,-std,label='BGEP STD',color='grey',alpha=0.2)
    ax.set_title(buoy_names[count])
    ax.set_ylabel('(FOAM - BGEP) / BGEP STD',labelpad=pads[count],fontsize = 12)
    ax.axhline(0,linestyle='dashed',color='k')
    
    ax.set_xticks([0,31,61,92,123,151,182]) 
    ax.set_xlim(0,212) 
    ax.set_xticklabels(['$1^{st}$ Oct','$1^{st}$ Nov', '$1^{st}$ Dec','$1^{st}$ Jan','$1^{st}$ Feb',
                        '$1^{st}$ Mar','$1^{st}$ Apr'])

**Comment by bendichter** [comment]
If you want to set the xticks directly, you'll need to do it by subplot. First of all, I would change to this:

```
bax = brokenaxes(ylims=((-3, 5.5), (19, 22)), hspace=0.2, subplot_spec=spec[count])
```
A brokenaxes object is *not* an Axes object, so this should clarify that a bit. To get the underlying axes, use `bax.axs`. Then set the xticks on the individual underlying axes.
