### ISSUE TITLE
create subplots not working

### ISSUE THREAD

**Issue by andreabacilieri** [bendichter/brokenaxes#99]
When using your code to create subplots with broken axis, the following error is produced

AttributeError: 'Axes' object has no attribute 'is_last_row'

**Comment by am-thyst** [comment]
Could you please provide a full script for us to reproduce this error? Also, include your versions for matplotlib and brokenaxes.

I had a similar issue with an old version of brokenaxes, but it is fixed with brokenaxes=0.5.5 and matplotlib=3.7.1.
